name: 'pr-build'

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  Checks:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: install
        run: npm ci

      - name: unit tests
        run: npm run test
